name: Production deployment

on:
  workflow_dispatch:

jobs:
  checkout:
    runs-on: [self-hosted, prod]
    environment: prod
    steps:
      - name: Checkout
        uses: actions/checkout@v4

  setup-env:
    runs-on: [self-hosted, prod]
    environment: prod
    needs: checkout
    steps:
      - name: Create .env file
        run: |
          cat > .env << EOF
          APP_MESSAGE_PREFIX=${{ vars.APP_MESSAGE_PREFIX }}
          DB_HOST=${{ vars.DB_HOST }}
          DB_HOST=${{ vars.DB_HOST }}
          DB_PORT=${{ vars.DB_PORT }}
          DB_USER=${{ vars.DB_USER }}
          DB_PASSWORD=${{ secrets.DB_PASSWORD }}
          DB_DATABASE=${{ vars.DB_DATABASE }}
          DB_SYNC=${{ vars.DB_SYNC }}
          JWT_TOKEN=${{ secrets.JWT_TOKEN }}
          JWT_EXPIRES_IN=${{ vars.JWT_EXPIRES_IN }}
          APP_PORT=${{ vars.APP_PORT }}
          EOF

  build:
    runs-on: [self-hosted, prod]
    environment: prod
    needs: setup-env
    steps:
      - name: Install dependencies
        run: npm ci

      - name: Build
        run: npm run build

  deploy:
    runs-on: [self-hosted, prod]
    environment: prod
    needs: build
    steps:
      - name: Stop existing app
        run: pm2 stop tasks-app || true

      - name: Run migrations and start app
        run: |
          APP_PORT=${{ vars.APP_PORT }} pm2 start npm --name "tasks-app" -- run start:prod

      - name: Save pm2 process list
        run: pm2 save